name = "cyberledger-subsystem"
main = "src/index.ts"
compatibility_date = "2026-08-06"

[build]
command = "npm run build"

[observability]
enabled = true

[triggers]
crons = [ ]

[vars]

[kv_namespaces]

[r2_buckets]

[d1_databases]

[ai]
